In [3]:
import numpy as np

arr = np.array([10, 20, 30, 41,55])
print(type(arr))
print(arr)
print(arr.shape)

<class 'numpy.ndarray'>
[10 20 30 41 55]
(5,)


### 백터화 연산 : 배열의 각 원소에 대한 반복연산을 하나의 명령어로 처리 가능

In [5]:
data = [0, 1, 2, 4, 8, 10]
arr = np.array(data)
arr *= 2
print(arr)

[0 2 4 8]


In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

result = 2*a +b
print(result)

result = a == 2          # result = (a == 2)
print(result)

result = (a==2) & (b>10)
print(result)

[12 24 36]
[False  True False]
[False  True False]


### 2차원 배열

In [11]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr)
print(arr.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [13]:
# 행의 갯수, 열의 갯수
print(len(arr), len(arr[0]))

2 3


### 3차원 배열

In [30]:
arr = np.array([[[1, 2, 3, 4], [4, 5, 6, 7], [4, 5, 6, 7]], 
                [[7, 8,9, 10], [7, 8, 9, 11], [10, 11, 12, 13]]])

print(arr.shape)
print(len(arr), len(arr[0]), len(arr[0][0]))
print(arr.ndim)              #3차원

(2, 3, 4)
2 3 4
3


In [33]:
a = np.array(1)
print(a.ndim)
print(a.shape)

0
()


### 배열의 인덱싱

In [40]:
arr = np.array([0, 1, 2, 3, 4])
print(arr[2], arr[-1])

arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr[0,0], arr[0,1], arr[-1, -1])

2 4
0 1 5


In [92]:
# fancy indexing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr[idx])
print(arr % 2)
print(arr % 2 == 0)
print(arr[arr % 2])

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

#[[1, 4], [5, 8], [9, 12]]
print(arr[:, [0, -1]])
print(arr[[2, 0, 1], :])

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라
# 이 배열에서 4로 나누면 1이 남는 수를 찾으라
# 이 배열에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라
idx = (arr % 3 == 0)
print(arr[idx])

idx = (arr % 4 == 1) & (arr > 4)
print(arr[idx])

idx = (arr % 3 == 0) & (arr % 4 == 1) & (arr > 4)
print(arr[idx])

[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 1 0 1 0 1 0 1 0 1]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[ 3  6  9 12 15 18]
[ 5  9 13 17]
[9]


### 배열의 슬라이싱

In [45]:
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

print(arr[0, :])
print(arr[:, 0])
print(arr[1, 1:])

[0 1 2 3]
[0 4]
[5 6 7]


### NumPy의 자료형

    b : 불리언                         b
    i : 정수                           i8
    u : 부호 없는 정수                  u8
    f : 부동 소수점                     f8
    c : 복수 부동소수점                 c16
    O : 객체
    S : 바이트 문자열                   S24(24글자)
    U : 유니코드 문자열                 U24

In [62]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = np.array([1.0, 2.0, 3.0])
print(arr.dtype)

arr = np.array([1, 2, 3.0])
print(arr.dtype)

int32
float64
float64


In [65]:
arr = np.array([1, 2, 3], dtype='f')
print(arr.dtype)
print(arr[0] + arr[1])

arr = np.array([1, 2, 3], dtype='U')
print(arr.dtype)
print(arr[0] + arr[1])

float32
3.0
<U1
12


### 배열 생성

In [89]:
a = np.zeros(5)
print(a)

b = np.zeros((2, 3), dtype='i')
print(b, b.dtype)

str = np.zeros(5, dtype='U4')
str[0] = 'abcd'
str[1] = 'ABCDF'    #dtype이 U4이므로 F가 짤린다.
print(str)

d = np.ones((2, 3, 4))
print(d)

# 크기를 명시하지 않고 다른 배열과 크기를 맞춰서 생성
e = np.ones_like(b, dtype='f')
print(e)

f = np.empty((4, 3))
print(f)

# arange
print(np.arange(10))
print(np.arange(3, 21, 2))

# linspace (구간 수만큼 분할)
print(np.linspace(0, 100, 5))

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]] int32
['abcd' 'ABCD' '' '' '']
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.24399158e-314 8.48798317e-314 1.06099790e-313]
 [1.48539705e-313 1.06099790e-313 1.48539705e-313]
 [1.69759663e-313 2.12199579e-313 1.69759663e-313]
 [2.33419537e-313 2.33419537e-313 2.75859453e-313]]
[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13 15 17 19]
[  0.  25.  50.  75. 100.]
